[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Force local-only execution without external RPC calls
no_storage_caching = true
gas_reports = ["*"]

# Remappings go here, outside of rpc_endpoints
remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[fuzz]
runs = 128

[invariant]
runs = 20
depth = 8
fail_on_revert = false
